// Code generated by github.com/99designs/gqlgen, DO NOT EDIT.

package model

type CreateTowerInput struct {
	Name        string  `json:"name"`
	Description *string `json:"description,omitempty"`
}

type UpdateTowerInput struct {
	ID          string  `json:"id"`
	Name        *string `json:"name,omitempty"`
	Description *string `json:"description,omitempty"`
}

type CreateFloorInput struct {
	TowerID     string  `json:"towerId"`
	Number      string  `json:"number"`
	Description *string `json:"description,omitempty"`
}

type UpdateFloorInput struct {
	ID          string  `json:"id"`
	Number      *string `json:"number,omitempty"`
	Description *string `json:"description,omitempty"`
}

type CreateApartmentInput struct {
	FloorID   string   `json:"floorId"`
	Number    string   `json:"number"`
	Bedrooms  *int     `json:"bedrooms,omitempty"`
	Area      *string  `json:"area,omitempty"`
	Price     *float64 `json:"price,omitempty"`
	Available bool     `json:"available"`
}

type UpdateApartmentInput struct {
	ID        string   `json:"id"`
	Number    *string  `json:"number,omitempty"`
	Bedrooms  *int     `json:"bedrooms,omitempty"`
	Area      *string  `json:"area,omitempty"`
	Price     *float64 `json:"price,omitempty"`
	Available *bool    `json:"available,omitempty"`
}

type ApartmentSearchInput struct {
	Query    *string  `json:"query,omitempty"`
	Bedrooms *int     `json:"bedrooms,omitempty"`
	Suites   *int     `json:"suites,omitempty"`
	TowerID  *string  `json:"towerId,omitempty"`
	PriceMin *float64 `json:"priceMin,omitempty"`
	PriceMax *float64 `json:"priceMax,omitempty"`
}

type ApartmentFilter struct {
	Bedrooms  *int     `json:"bedrooms,omitempty"`
	Suites    *int     `json:"suites,omitempty"`
	PriceMin  *float64 `json:"priceMin,omitempty"`
	PriceMax  *float64 `json:"priceMax,omitempty"`
	Available *bool    `json:"available,omitempty"`
}