# =============================================================================
# TRAEFIK - REVERSE PROXY E LOAD BALANCER
# =============================================================================
# Configuração do Traefik para o ambiente de produção
# Suporte aos subdomínios: terra-allwert.online, db.terra-allwert.online, minio.terra-allwert.online
# =============================================================================

version: '3.8'

services:
  traefik:
    image: traefik:v2.10
    command:
      # API Dashboard
      - --api.dashboard=true
      - --api.insecure=false
      
      # Docker provider
      - --providers.docker=true
      - --providers.docker.swarmMode=true
      - --providers.docker.exposedbydefault=false
      - --providers.docker.network=TerraAllWertNet
      
      # Entry points
      - --entrypoints.web.address=:80
      - --entrypoints.websecure.address=:443
      - --entrypoints.postgres.address=:5432  # Para acesso ao PostgreSQL
      
      # Let's Encrypt (SSL automático)
      - --certificatesresolvers.letsencrypt.acme.email=admin@terra-allwert.online
      - --certificatesresolvers.letsencrypt.acme.storage=/letsencrypt/acme.json
      - --certificatesresolvers.letsencrypt.acme.httpchallenge.entrypoint=web
      
      # Redirect HTTP para HTTPS
      - --entrypoints.web.http.redirections.entrypoint.to=websecure
      - --entrypoints.web.http.redirections.entrypoint.scheme=https
      
      # Logs
      - --log.level=INFO
      - --accesslog=true
      
    ports:
      - "80:80"      # HTTP
      - "443:443"    # HTTPS
      - "5432:5432"  # PostgreSQL (opcional - para desenvolvimento)
      - "8080:8080"  # Traefik Dashboard
      
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - traefik_letsencrypt:/letsencrypt
      
    networks:
      - TerraAllWertNet
      
    deploy:
      replicas: 1
      placement:
        constraints:
          - node.role == manager
      restart_policy:
        condition: on-failure
      resources:
        limits:
          cpus: "0.2"
          memory: 128M
        reservations:
          cpus: "0.1"
          memory: 64M
      labels:
        # Dashboard do Traefik
        - "traefik.enable=true"
        - "traefik.http.routers.traefik-dashboard.rule=Host(`traefik.terra-allwert.online`)"
        - "traefik.http.routers.traefik-dashboard.entrypoints=websecure"
        - "traefik.http.routers.traefik-dashboard.tls.certresolver=letsencrypt"
        - "traefik.http.routers.traefik-dashboard.service=api@internal"
        - "traefik.http.routers.traefik-dashboard.middlewares=auth"
        
        # Autenticação básica para o dashboard
        # Usuário: admin, Senha: password (altere isso!)
        # Gere nova senha com: htpasswd -nb admin password
        - "traefik.http.middlewares.auth.basicauth.users=admin:$$2y$$10$$rO3IzLfK8XYz4QjF3Rn/6OkX5YGT.tR8Qw9N0kL5.3F9g8H3d5E4"
        
    healthcheck:
      test: ["CMD", "traefik", "healthcheck"]
      interval: 30s
      timeout: 3s
      retries: 3

# =============================================================================
# REDES
# =============================================================================
networks:
  TerraAllWertNet:
    external: true
    name: TerraAllWertNet

# =============================================================================
# VOLUMES
# =============================================================================
volumes:
  traefik_letsencrypt:
    driver: local